name: build-mod
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # 直接下載 Gradle 8.8，跳過 gradle wrapper
      - name: Build with Gradle 8.8 (no wrapper)
        run: |
          set -e
          curl -sL https://services.gradle.org/distributions/gradle-8.8-bin.zip -o gradle-8.8-bin.zip
          unzip -q gradle-8.8-bin.zip
          ./gradle-8.8/bin/gradle --version
          ./gradle-8.8/bin/gradle --no-daemon --stacktrace --info build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: auto-enchant-mod
          path: build/libs/*.jar
          if-no-files-found: error

